# This is a basic workflow to help you get started with Actions

name: FIRST WORKFLOW

# Controls when the workflow will run
on: worksflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs :
  runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     # Runs a single command using the runners shell
      - name: Print line
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: print bye 
        run : echo " bye git"
       
